# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[social]]
    name = "Github"
    identifier = "github"
    url = "https://github.com/proxyerium/"
    weight = 1
    params.icon = "brand-github"
[[social]]
    name = "Steam"
    identifier = "steam"
    url = "https://steamcommunity.com/id/proxy_yuwtnnv/"
    weight = 2
    params.icon = "brand-steam"
[[social]]
    name = "Telegram"
    identifier = "telegram"
    url = "https://t.me/proxy_yuwtnnv"
    weight = 3
    params.icon = "brand-telegram"
[[social]]
    name = "Discord"
    identifier = "discord"
    url = "https://discord.com/users/994616767534076049"
    weight = 4
    params.icon = "brand-discord"
